name: build, push, deploy and cleanup
on: 
  push:
    branches: 
      - "feature/new-ci-cd"

jobs:
  build_and_push:
    runs-on: self-hosted
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: login to nexus
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD}}
      - name: build and push
        run: |
          ${{ steps.vars.outputs.sha_short }}
          docker build -t ${{ secrets.NEXUS_HOST }}/dagestanfront:latest -t ${{ secrets.NEXUS_HOST }}/dagestanfront:${{ github.run_number }} .
      - name: push docker image
        run: |
          docker push ${{ secrets.NEXUS_HOST }}/dagestanfront:latest
          docker push ${{ secrets.NEXUS_HOST }}/dagestanfront:${{ github.run_number }}


  deploy:
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: Docker stop, pull and up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker-compose pull
            docker-compose stop
            docker-compose up -d  

  cleanup:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: Throw away all the garbage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script:
            docker system prune -f --filter "label!=keep"

