name: linting 
on: [ push ]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "20.0" ]
    steps:
      - uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install pnmp
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install dependencies
        run: pnpm install
      - name: eslinting
        run: |
          pnpm codecheck 

